version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8088:8088 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - skillpedia-postgres          # Uncomment this when using postgres.
    networks:
      - skillpedia


  skillpedia-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - skillpedia
   
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - skillpedia-postgres
    ports:
      - "5050:80"
    networks:
      - skillpedia
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  # Uncomment this when using postgres.

# Networks to be created to facilitate communication between containers
networks:
  skillpedia:
    driver: bridge

